server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ClinicAppointmentSystem?createDatabaseIfNotExist=true # &useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true

    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        jdbc:
          useUnicode: true
          character_encoding: UTF-8
          connection:
            characterEncoding: UTF-8
        connection:
          CharSet: UTF-8
          useUnicode: true
      dialect: org.hibernate.dialect.MySQLDialect
      format_sql: true

    database-platform: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB



api:
  prefix: /api/v1

jwt:
  secret-key: "dangthanhphucbt25122k3@gmail.com"
  expiration: 86400 # 1 day = 60 * 60 * 24
  expiration-refresh: 172800 #2 days = 2 * 24 * 60 * 60

